panss/urls.py
from django.conf.urls import include, url

urlpatterns = [
#show previous panss ratings
    url(r'^(?P<patient_id>\d+)/$', 'panss.views.panss'),
    url(r'^(?P<patient_id>\d+)/(?P<panss_id>\d+)/$', 'charts.views.PanssItemChart'),




#create new panss rating
    url(r'^new/(?P<patient_id>\d+)/$', 'panss.views.panssForm'),
    url(r'^admission/(?P<patient_id>\d+)/$', 'panss.views.panssFormFull'),
    url(r'^full/(?P<patient_id>\d+)/$', 'panss.views.panssFormFull'),
    url(r'^rating-targets/(?P<patient_id>\d+)/(?P<fullpanss_id>\d+)$', 'panss.views.panssTargets'),



#trying to paginate forms
   # url(r'^panss/new/(?P<patient_id>\d+)/$', PANSSWizard.as_view([PANSSPositiveForm, PANSSNegativeForm, PANSSGeneralForm])),

]

symptom_tracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'symptom_tracker.views.home'),
    url(r'^patient/', include('rating.urls')),
    url(r'^patient/panss/', include('panss.urls')),
    url(r'^chart/', include('charts.urls')),
    url(r'^accounts/', include('userprofile.urls')),
    url(r'^patient/', include('events.urls')),


    # User auth urls
    url(r'^accounts/login/$', 'symptom_tracker.views.login'),
    url(r'^accounts/auth/$', 'symptom_tracker.views.auth_view'),
    url(r'^accounts/logout/$', 'symptom_tracker.views.logout'),
    url(r'^accounts/loggedin/$', 'symptom_tracker.views.loggedin'),
    url(r'^accounts/invalid/$', 'symptom_tracker.views.invalid_login'),
    url(r'^accounts/register/$', 'symptom_tracker.views.register_user'),
    url(r'^accounts/register_success/$', 'symptom_tracker.views.register_success'),


]


if not settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

symptom_tracker/forms.py
__author__ = 'felixdransfield'
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

symptom_tracker/views.py
__author__ = 'felixdransfield'

from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf
from forms import MyRegistrationForm
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save


def home(request):
    return render(request, "home.html")


def login(request):
    c = {}
    c.update(csrf(request))
    return render(request, 'login.html', c)

def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/accounts/loggedin')
    else:
        return HttpResponseRedirect('/accounts/invalid')

def loggedin(request):
    return render(request, 'loggedin.html',
        {'full_name': request.user.username})

def invalid_login(request):
    return render(request, 'invalid_login.html')

def logout(request):
    auth.logout(request)
    return render(request, 'logout.html')

def register_user(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/accounts/register_success')


    args = {}
    args.update(csrf(request))

    args['form'] = MyRegistrationForm()

    return render(request, 'register.html', args)

def register_success(request):
    return render(request, 'register_success.html')


# signal to add new user to default group
def default_group(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='4'))
post_save.connect(default_group, sender=User)

symptom_tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <title>{% block title %}Symptom Tracker beta{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "assets/css/default.css" %}">
    <script type=”text/javascript” src="{% static "assets/js/jquery-2.1.4.min.js" %}"></script>
    <script type=”text/javascript” src="{% static "assets/js/Highcharts-4.1.7/js/highcharts.js" %}"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <script>

  </script>

</head>
<body>
     <div class ="header">
         <div class="headerContainer">
            <div class="title">Symptom-Tracker<span class="sub-title">BETA</span></div>

             <div id="headerNav">
                 {% if user.is_authenticated %}
                 <span class="loggedin">Logged in as: {{ user.get_username }}</span>
                 {% else %}
                 <span class="loggedin red">Not logged in</span>
                  {% endif %}
                 <a href="/"><i class="fa fa-home fa-2x" title="Home"></i></a>
                 <a href="/accounts/profile/{{ user.id }}"><i class="fa fa-user-md fa-2x" title="Profile"></i></a>
                 <a href="/accounts/logout/"><i class="fa fa-sign-out fa-2x" title="Logout"></i></a>
             </div>
         </div>
     </div>

     <div id ="page">

        <div id ="sidebar">
            {% block sidebar%}
            <ul>
                {% if user.is_authenticated %}
                    <a href="/patient/all"> <li><p>Patients</p></li></a>
                    <a href="/accounts/"> <li><p>Users</p></li></a>

                {% else %}
                    <a href="/accounts/login"> <li><p>Login</p></li></a>
                    <a href="/accounts/register"> <li><p>Register</p></li></a>
                {% endif %}

                {% if request.user.is_superuser %}
                    <a href="/admin"> <li><p>Admin</p></li></a>
                {% endif %}

            </ul>
            {% endblock %}
        </div>

        <div id="content">
            <div id="contentContainer">
            {% block content %}{% endblock %}
            </div>
        </div>

     </div>

</body>
</html>

symptom_tracker/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>HOME PAGE</h1>


{% endblock %}

symptom_tracker/templates/invalid_login.html
{% extends "base.html" %}

{% block content %}

  <h2>Your login details are invalid!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again.</p>

{% endblock %}

symptom_tracker/templates/loggedin.html
{% extends "base.html" %}

{% block content %}

  <h2>Hi {{full_name}} you are now logged in!</h2>
  <p>Click <a href="/accounts/logout/">here</a> to logout</p>
    <p>Click <a href="/accounts/profile/edit/{{ user.id }}" >here</a> to edit your profile</p>
  



{% endblock %}

symptom_tracker/templates/login.html
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
        <p class="error">Sorry, that's not a username or password</p>
    {% endif %}

<div class="centered">

<h1>Login</h1>



    <form action="/accounts/auth/" method="post">{% csrf_token %}
        <label for="username">User name:</label>
        <input type="text" name="username" value="" id="username">
        <label for="password">Password:</label>
        <input type="password" name="password" value="password">



       <input type="submit" value="login" class="btn blue"  />

    </form>
<br><br>
<h2>Not Registered? click here to create an account</h2>
<a href="/accounts/register" class="btn blue">Register</a>

</div>

{% endblock %}

symptom_tracker/templates/logout.html
{% extends "base.html" %}

{% block content %}

  <h2>Logged out!</h2>
  <p>Click <a href="/accounts/login/">here</a> to login again</p>

{% endblock %}

symptom_tracker/templates/register.html
{% extends "base.html" %}

{% block content %}
  
  <h1>Register</h1>
  
  {% for field in form %}
    {{field.error}}

  {% endfor %}


<form action="/accounts/register/" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.username.errors }}
        <label for="id_Username">Username:</label>
        {{ form.username }}
    </div>
    <div class="fieldWrapper">
        {{ form.email.errors }}
        <label for="id_email">Email Address:</label>
        {{ form.email }}
    </div>
    <div class="fieldWrapper">
        {{ form.password1.errors }}
        <label for="id_password1">Password:</label>
        {{ form.password1 }}
    </div>
    <div class="fieldWrapper">
        {{ form.password2.errors }}
        <label for="id_password2">Password confirmation:</label>
        {{ form.password2 }}
    </div>
    <br>
    <input type="submit" value="Register" class="btn blue"/>
</form>

{% endblock %}

symptom_tracker/templates/register_success.html
{% extends "base.html" %}

{% block content %}

    <h2>You have registered</h2>
    <p>Click <a href="/accounts/login/">here</a> to login </p>

{% endblock %}